spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_story?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 150677252870-78tlj6v2mm653alhodqr9t5br5fu5bs0.apps.googleusercontent.com
            clientSecret: ZptsDAPoVjn7DzVYbzSDNt1v
            redirect-uri: http://localhost:8080/oauth2/callback/google #http://localhost:8080/login/oauth2/code/google


